#include <iostream>
#include <stdexcept>

using namespace std;

class QueueOverflowException : public exception
{
};

class QueueUnderflowException : public exception
{
};

template <typename T>
class Queue
{
private:
    T *data;
    int front, rear, size, capacity;

public:
    Queue(int cap) : front(0), rear(0), size(0), capacity(cap)
    {
        data = new T[capacity];
    }

    ~Queue()
    {
        delete[] data;
    }

    void enqueue(const T &value)
    {
        if (size == capacity)
            throw QueueOverflowException();

        data[rear] = value;
        rear = (rear + 1) % capacity;
        size++;
    }

    T dequeue()
    {
        if (size == 0)
            throw QueueUnderflowException();

        T val = data[front];
        front = (front + 1) % capacity;
        size--;
        return val;
    }

    bool isEmpty() const { return size == 0; }
    bool isFull() const { return size == capacity; }
};

int main()
{
    Queue<int> q(2);

    try
    {
        cout << "Attempting to enqueue to a full queue..." << endl;
        q.enqueue(10);
        q.enqueue(20);
        q.enqueue(30); //throw
    }
    catch (const QueueOverflowException &e)
    {
        cout << "Caught QueueOverflowException what(): " << e.what() << endl;
    }

    try
    {
        cout << "Attempting to dequeue from an empty queue..." << endl;
        Queue<int> emptyQueue(2);
        emptyQueue.dequeue(); //throw
    }
    catch (const QueueUnderflowException &e)
    {
        cout << "Caught QueueUnderflowException what(): " << e.what() << endl;
    }

    return 0;
}
